### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [jpearson0525/micromapST#3]
Dear Maintainer,

You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

micromapST imports 'rgdal', 'rgeos', 'maptools' using maptools::spRbind maptools::unionSpatialPolygons rgdal::CRSargs rgdal::new_proj_and_gdal rgdal::readOGR rgdal::rgdal_extSoftVersion rgdal::set_P6_datum_hard_fail rgdal::set_rgdal_show_exportToProj4_warnings rgdal::set_thin_PROJ6_warnings rgdal::writeOGR, found by `pkgapi`, as in NAMESPACE. I think that you will find plenty of hints through https://r-spatial.org/r/2023/04/10/evolution3.html and in the example conversion ASDAR scripts from retiring packages to sf; see also https://github.com/r-spatial/evolution/blob/main/pkgapi_230305_refs.csv. Please let me know if you have a draft mitigated version of the package that you'd like me to run CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path. I don't think  you are using this repository for development, so I can't just watch for changes. Please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
Only three months remain to keep your package on CRAN. Please take action now!

**Comment by jpearson0525** [comment]
We appreciate you advanced notice of the developments.  Release 3.0.0 of micromapST should address any issues caused by the retirement of maptools, rgeos and rgdal.   Release 3.0.0 has completed it release to CRAN and Github. Cheers,

**Comment by rsbivand** [comment]
@jpearson0525 Thanks, confirmed in https://github.com/r-spatial/evolution/blob/main/watchlist_output/summary_2023-08-11.txt.
